# Generated by Django 3.2.5 on 2022-05-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
